

#! APP DEPLOY DATA
APP_VERSION = '0001'

#! DEFAULTS
DEFAULT_PORT = 8421
DEFAULT_SERVERNAME = 'localhost'


#! VERBOS
VERB_UPDATE = 'UPDATE'
VERB_POWERON = 'POWERON'
VERB_POWEROFF = 'POWEROFF'
VERB_BYE = 'BYE'
VERB_GET_VERSION = 'VERSION'

#!Geral
CHAR_SET = 'utf-8'
BUFSIZE = 8096

#! RESPOSTAS
RESP_OK = 0
RESP_ERROR = 500
RESP_OFFLINE = 600